spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: sa
  password: sa
spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server.port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


camunda:
  bpm:
    generic-properties:
      properties:
        historyCleanupJobLogTimeToLive: P1D
        batchOperationHistoryTimeToLive: P1D
        historyCleanupStrategy: removalTimeBased
        historyCleanupBatchWindowStartTime: '22:00'
        historyCleanupBatchWindowEndTime: '06:00'
        historyRemovalTimeStrategy: end
        historyCleanupDegreeOfParallelism: 1
        historyCleanupBatchSize: 50
        historyCleanupEnabled: true
        historyTimeToLive: P2D
    job-execution:
      core-pool-size: 3
      max-pool-size: 10
    history-level: ACTIVITY
    history-level-default: ACTIVITY
    default-number-of-retries: 7
    authorization:
      enabled: false
    webapp:
      index-redirect-enabled: true
      application-path: /retail-camunda
